import { Product } from "./types/Product";

export const SampleProducts: Product[] = [
    {
        id: 1,
        name: 'Coffee Table',
        slug: "Coffee Table",
        image: "/images/coffee table.jpg",
        category: "Tables",
        brand: "Swedish",
        price: 180,
        CountInStock: 15,
        description: "high quality",
        rating: 4.0,
        numReviews: 10,
    },
    {
        id: 2,
        name: 'Conference Table',
        slug: "Conference Table",
        image: "/images/conference table.jpg",
        category: "Tables",
        brand: "Swedish",
        price: 540,
        CountInStock: 10,
        description: "high quality",
        rating: 4.2,
        numReviews: 15,
    },
    {
        id: 3,
        name: 'Dinning Table',
        slug: "Dining Table",
        image: "/images/dinning table.jpg",
        category: "Tables",
        brand: "Swedish",
        price: 480,
        CountInStock: 6,
        description: "high quality",
        rating: 4.7,
        numReviews: 12,
    },
    {
        id: '4',
        name: 'Outdoor Table',
        slug: "Outdoor Table",
        image: "/images/outdoortable.jpeg",
        category: "Tables",
        brand: "Swedish",
        price: 160,
        CountInStock: 9,
        description: "high quality",
        rating: 3.9,
        numReviews: 12,
    },
];
