import { Product } from "./types/Product";

export const SampleProducts: Product[] = [
    {
        id: '1',
        name: 'Coffee Table',
        slug: "coffee-table",
        image: "images/coffee-table.jpg",
        category: "Tables",
        brand: "Swedish",
        price: 180,
        CountInStock: 15,
        description: "High-quality coffee table",
        rating: 4.0,
        numReviews: 10,
    },
    {
        id: '2',
        name: 'Conference Table',
        slug: "conference-table",
        image: "images/conference-table.jpg",
        category: "Tables",
        brand: "Swedish",
        price: 540,
        CountInStock: 10,
        description: "High-quality conference table",
        rating: 4.2,
        numReviews: 15,
    },
    {
        id: '3',
        name: 'Dining Table',
        slug: "dining-table",
        image: "images/dining-table.jpg",
        category: "Tables",
        brand: "Swedish",
        price: 480,
        CountInStock: 6,
        description: "High-quality dining table",
        rating: 4.7,
        numReviews: 12,
    },
    {
        id: '4',
        name: 'Outdoor Table',
        slug: "outdoor-table",
        image: "images/outdoor-table.jpg",
        category: "Tables",
        brand: "Swedish",
        price: 160,
        CountInStock: 9,
        description: "High-quality outdoor table",
        rating: 3.9,
        numReviews: 12,
    },
];
